Use GNUInstallDirs for install paths
opcm/pcm pull request #410
Opened 2022-06-20 18:46 UTC by hexchain

Some distros may have special requirements on install paths. For example, Arch Linux expects all binaries to be installed into `/usr/bin`. To make packaging easier for these distros, use `GNUInstallDirs` to allow customization of these paths (using e.g. `-DCMAKE_INSTALL_SBINDIR=bin`) with sane defaults.

The only difference in the result is that the documents are now installed to `prefix/share/doc/PCM` (uppercase) instead of `prefix/share/doc/pcm`, because `CMAKE_INSTALL_DOCDIR` uses the project name. If this is not desired, let me know and I'll change it.

2022-06-21 07:14 UTC, opcm commented
thanks for the patch

2022-06-22 15:28 UTC, MarkovaMaria requested changes
Hello @hexchain, 
Could you please update pcm.spec file where old path to docs is used currently? 
```
 $ grep -R "share/doc/pcm/"
pcm.spec:/usr/share/doc/pcm/CUSTOM-COMPILE-OPTIONS.md
pcm.spec:/usr/share/doc/pcm/DOCKER_README.md
pcm.spec:/usr/share/doc/pcm/ENVVAR_README.md
pcm.spec:/usr/share/doc/pcm/FAQ.md
pcm.spec:/usr/share/doc/pcm/FREEBSD_HOWTO.txt
pcm.spec:/usr/share/doc/pcm/LINUX_HOWTO.txt
pcm.spec:/usr/share/doc/pcm/MAC_HOWTO.txt
pcm.spec:/usr/share/doc/pcm/PCM-EXPORTER.md
pcm.spec:/usr/share/doc/pcm/PCM-SENSOR-SERVER-README.md
pcm.spec:/usr/share/doc/pcm/PCM_RAW_README.md
pcm.spec:/usr/share/doc/pcm/README.md
pcm.spec:/usr/share/doc/pcm/WINDOWS_HOWTO.md
pcm.spec:/usr/share/doc/pcm/license.txt
```
Rest of patch looks good to me. Thanks!

2022-06-22 15:34 UTC, hexchain commented
Done.

2022-06-22 15:35 UTC, MarkovaMaria approved these changes

2022-06-22 15:54 UTC, merged